rebuild-ci-container:
  variables:
    QT_VERSION: "5.15.2"
  only:
    changes:
      - Dockerfile
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}"
      --build-arg QT_VERSION="${QT_VERSION}"
      --build-arg QT_INSTALLER_JWT_TOKEN="${QT_INSTALLER_JWT_TOKEN}"
